Various changes to support error ids and portability

diff --git a/bin/dotfile b/bin/dotfile
--- a/bin/dotfile
+++ b/bin/dotfile
@@ -12,6 +12,7 @@
 #-- Constants -------------------------------------------------------------------------------------------------------
 
 ERR_UNKNOWN_CMD=1
+ERR_INVALID_LOG_PATH=2
 SUCCESS=0
 
 
@@ -1375,6 +1376,7 @@ function teardown_role_links
     # First step is to create links if configured and the role contains them
     if [[ -d "${ROLE_LINK}" ]]; then
     
+        # Look at direct children
         TARGETS=$(find "$ROLE_LINK" -maxdepth 1 -mindepth 1 2>/dev/null | reverse_lines)
         
         # Go through all the files/folders found in the links folder as we need to point to them as symbolic
@@ -1460,7 +1462,7 @@ then
     . "$DOTFILES_ADMIN_CONFIG"
     if [[ $? -ne 0 ]]
     then
-        printf "ERROR: Could not source '%s'.  Exiting\n" ERROR "${DOTFILES_ADMIN_CONFIG}" >&2
+        printf "%s: Could not source '%s'.  Exiting\n" ERROR "${DOTFILES_ADMIN_CONFIG}" >&2
         return 1
     fi
 fi
@@ -1476,19 +1478,19 @@ fi
 # Check if the log is writeable
 if [[ ! -r "$DOTFILES_LOG" ]]; then
     printf "%s: The value of %s [%s] is not readable.  Exiting\n" ERROR DOTFILES_LOG "$DOTFILES_LOG" >&2
-    return 1
+    return $ERR_INVALID_LOG_PATH
 fi
 
 # Check if the log is writeable
 if [[ ! -w "$DOTFILES_LOG" ]]; then
-    echo "ERROR: The value of DOTFILES_LOG [$DOTFILES_LOG] is not writeable.  Exiting" >&2
-    return 1
+    printf "%s: The value of %s [%s] is not writeable.  Exiting\n" ERROR DOTFILES_LOG "$DOTFILES_LOG" >&2
+    return $ERR_INVALID_LOG_PATH
 fi
 
 log_it INFO PARAMS "dotfile $@"
 if [[ $? -ne 0 ]]; then
-    echo "ERROR: Could not write to DOTFILES_LOG [$DOTFILES_LOG] is not a valid file.  Exiting" >&2
-    return 1
+    printf "%s: Could not write to %s [%s] is not a valid file.  Exiting\n" ERROR DOTFILES_LOG "$DOTFILES_LOG" >&2
+    return $ERR_INVALID_LOG_PATH
 fi
 
 
@@ -1553,7 +1555,7 @@ while [[ $# -ne 0 ]]; do
                                  ;;
 
         -h | --help            ) usage
-                                 return 0
+                                 return $SUCCESS
                                  ;;
                                  
         *                      ) break
@@ -1568,14 +1570,14 @@ done
 if [[ $# -lt 2 ]]; then
     if [[ $# -lt 1 || ( "$1" != "list" && "$1" != "reset" ) ]]; then
         usage >&2
-        return 1
+        return $ERR_UNKNOWN_CMD
     fi
 fi
 
 MAIN_CMD="$1"
 shift
 
-# Basic validation and executing high level commands that dont erquire environment manipulation
+# Basic validation and executing high level commands that dont require environment manipulation
 case "$MAIN_CMD" in
 
     request            ) ;;
@@ -1598,8 +1600,8 @@ ROLE_LIST=$( echo "${DOTFILES_ROLES_PATH}" | sed 's/:/\n/g' | xargs -i find {} -
 
 # Very lightweight functionality that doesnt need to know of current role state etc
 if [[ "$MAIN_CMD" == "list" ]]; then
-    echo "${ROLE_LIST}"
-    return $?
+    printf "%s\n" "${ROLE_LIST}"
+    return $SUCCESS
 fi
 
 # Further commands interact directly with an already allocated role or a specific one that needs querying, reset is an exception as it has no arguments
